name: ðŸš€ Deploy b9_36151388 on push with FTP

on:
  push:
    branches:
      - master
    paths:
      - "projects/b9_36151388/html/bootstrap4/**"

jobs:
  deploy:
    name: ðŸŽ‰ Deploy to b9-36151388.22web.org
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2

      # - name: Use Node.js 14.x
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14.x

      # - name: Install node dependencies
      #   run: cd 200.vue2-ui && yarn install

      # - name: Build pages
      #   run: cd 200.vue2-ui && npm run build

      # - name: Install composer dependencies
      #   run: composer install

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b9_36151388
          # ftp password
          password: ${{ secrets.ftp_password }}
          # local dir
          local-dir: ./projects/b9_36151388/html/bootstrap4/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /b9-36151388.22web.org/htdocs/
          # File to Exclude
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/node_modules/**
